# Tap homebrew
tap 'homebrew/cask'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/core'
tap 'homebrew/boneyard'
tap 'homebrew/dev-tools'
tap 'homebrew/bundle'
tap 'homebrew/services'

# casks
cask 'google-chrome'
cask 'slack'
cask 'postman'
cask 'atom'
cask 'zoomus'
cask 'vscode'
cask 'dbeaver-community'

install 'yarn'
install 'git'
install 'postgresql'
install 'zsh'
install 'gpg'
